name: Build and Deploy
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install pyTelegramBotAPI boto3
      - name: Run Bot (Long Mode)
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          SQS_URL: ${{ secrets.SQS_URL }}
        run: timeout 360m python app/bot.py || echo "Finished"
