name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyTelegramBotAPI boto3
          
      - name: Run Bot 24/7 Mode
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          SQS_URL: ${{ secrets.SQS_URL }}
        run: |
          # הפקודה הזו אומרת למכונה לרוץ עד 360 דקות (6 שעות)
          timeout 360m python app/bot.py || echo "Timeout reached"
